# Generated by Django 3.1.6 on 2021-02-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumthread',
            old_name='thread_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='forumthread',
            old_name='thread_heading',
            new_name='heading',
        ),
    ]
